### ISSUE TITLE
Issues starting services with Ansible

### ISSUE THREAD

**Issue by crsmithdev** [defunctzombie/ansible-coreos-bootstrap#2]
I can't seem to get any services started using this approach.  Playbook:

```
- hosts: web
  remote_user: core
  tasks:

  - name: start etcd
    service: name=etcd.service state=started
```

Result:

```
coreos-web-01 | FAILED => failed to parse: Spawning container core-crsmithdev_ubuntu-latest on /var/lib/toolbox/core-crsmithdev_ubuntu-latest.
Press ^] three times within 1s to kill container.
{"msg": "service not found: etcd.service", "failed": true}

Container core-crsmithdev_ubuntu-latest failed with error code 1.
```

I can `systemctl start etcd.service` with no issues manually, however.

Any idea what might be going on?
